apiVersion: operator.curve.io/v1
kind: CurveCluster
metadata:
  name: my-cluster
  namespace: curvebs
spec:
  # Add fields here
  curveVersion:
    image: opencurvedocker/curvebs:v1.2
  nodes:
  - node1
  - node2
  - node3
  dataDirHostPath: "/curvebs/data"
  logDirHostPath: "/curvebs/log"
  etcd:
    port: 23880
    listenPort: 23890
  mds:
    port: 23970
    dummyPort: 23960
  storage:
    useSelectedNodes: false
    nodes:
    - node1
    - node2
    - node3
    port: 8200
    copysets: 100
    devices:
    - name: "/dev/sdb"
      mountPath: "/data/chunkserver0"
      percentage: 90
  snapShotClone:
    enable: true
    port: 5555
    dummyPort: 8083
    proxyPort: 8084
    s3Config:
      ak: minioadmin
      sk: minioadmin
      nosAddress: http://10.219.196.145:9000
      bucketName: curvebs

