apiVersion: operator.curve.io/v1
kind: CurveCluster
metadata:
  name: cluster-test1
  namespace: curvebs
spec:
  # Add fields here
  curveVersion:
    image: opencurvedocker/curvebs:v1.2
  nodes:
  - 10.219.196.145
  - 10.219.192.90
  - 10.219.196.150
  dataDirHostPath: "/curvebs/data"
  logDirHostPath: "/curvebs/log"
  etcd:
    port: 23820
    listenPort: 23830
  mds:
    port: 23990
    dummyPort: 23980
