apiVersion: operator.curve.io/v1
kind: CurveCluster
metadata:
  name: cluster-test1
  namespace: curvebs
spec:
  # Add fields here
  curveVersion:
    image: opencurvedocker/curvebs:v1.2
  nodes:
  - 10.219.196.145
  - 10.219.192.90
  - 10.219.196.150
  dataDirHostPath: "/curvebs/data"
  logDirHostPath: "/curvebs/log"
  etcd:
    port: 23880
    listenPort: 23890
  mds:
    port: 23970
    dummyPort: 23960
  storage:
    useSelectedNodes: false
    nodes:
    - node1
    - node2
    - node3
    port: 8200
    copysets: 100
    # - node3
    devices:
    - name: "/dev/sdb"
      mountPath: "/data/chunkserver0"
      percentage: 90
